# Generated by Django 5.1.6 on 2025-03-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messageversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefile',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='filename',
        ),
        migrations.AddField(
            model_name='messagefile',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='file_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
